name: flutter_multi_bloc_builder
description: MultiBlocBuilder is an implementation for building widgets that react to changes of multiple bloc states.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.0.0

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
